import numpy as np, matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
rom=np.load('mad_rom.npz'); mad=np.load('mad_mad.npz')
t,r,C,chi=rom['time'],rom['radius'],rom['C'],rom['chi']; mdot=mad['mdot']
g=np.isfinite(chi)&np.isfinite(C).all(axis=1)&(mdot>1e-4)
t,C,chi=t[g],C[g],chi[g]
Rd=(C*r).sum(1)/np.maximum(C.sum(1),1e-30)
Cin=C[:,r<=5.].mean(1)
fig=plt.figure(figsize=(7.4,6.2))
gs=fig.add_gridspec(2,2,height_ratios=[2.0,1.05],width_ratios=[40,1],
                    hspace=0.30,wspace=0.03)
a0=fig.add_subplot(gs[0,0]); cax=fig.add_subplot(gs[0,1])
a1=fig.add_subplot(gs[1,0],sharex=a0)
m=a0.pcolormesh(t,r,C.T,cmap='magma',vmin=0,vmax=1,shading='auto',rasterized=True)
a0.plot(t,Rd,color='w',lw=1.0,label=r'$R_{d,\rm eff}(t)$')
a0.axvline(7900,color='#39ffa2',lw=1.4,ls='--')
a0.text(8100,46,'stationary window',color='#39ffa2',fontsize=9,va='center')
a0.set_ylim(r.min(),50); a0.set_ylabel(r'$r\ [GM/c^{2}]$')
a0.legend(loc='lower right',fontsize=9,framealpha=0.9)
a0.set_title('(a) connectivity field reduced from the 2D MAD run',fontsize=11)
plt.setp(a0.get_xticklabels(),visible=False)
cb=fig.colorbar(m,cax=cax); cb.set_label(r'$C(r,t)$')
a1.plot(t,chi,color='#c0392b',lw=0.8)
a1.set_ylabel(r'$\varphi_{\rm BH}$',color='#c0392b')
a1.tick_params(axis='y',colors='#c0392b')
a1.axvline(7900,color='#2e9e6b',lw=1.4,ls='--')
a2=a1.twinx(); a2.plot(t,Cin,color='#2c3e6b',lw=0.8)
a2.set_ylabel(r'$C_{\rm in}$',color='#2c3e6b')
a2.tick_params(axis='y',colors='#2c3e6b')
a1.set_xlabel(r'$t\ [GM/c^{3}]$')
a1.set_title(r'(b) driver $\varphi_{\rm BH}(t)$ and endpoint $C_{\rm in}(t)=\langle C\rangle_{r\leq 5M}$',fontsize=10)
fig.savefig('crt.pdf',bbox_inches='tight')
fig.savefig('crt.png',dpi=300,bbox_inches='tight')
print('ok')
